Revrite backend in Golang + gRPC
bcc-code/bcc-media-tools pull request #6
Opened 2024-05-10 14:13 UTC by KillerX

It's functional, but not 100% ready for proper testing.

Missing things:

* Transcription editor is not done yet server side
* Go backend could be structured a touch better (everything in one package for now)
* Some data needs to be passed to the frontend to better display tracks (publish date, etc)

2024-05-13 20:35 UTC, KillerX commented
@andreasgangso this has feature parity (+ better BMM support) so we can merge if the code looks sane. The 2 things on the TODO will be done while I'm testing with "end" users.

2024-05-14 07:31 UTC, merged

2024-05-14 07:50 UTC, andreasgangso requested changes

2024-05-14 07:50 UTC, andreasgangso commented on frontend/pages/upload/bmm.vue
> +                    endpoint="http://localhost:8080/upload"
localhost

2024-05-14 07:50 UTC, andreasgangso commented on frontend/nuxt.config.ts
> +            grpcURL: "http://localhost:8080",
local stuff